name: Builder - Integration tests

on:
  # on changes to the main branch touching the builder
  push:
    branches: [main]

  # on PRs touching the builder
  pull_request:
    branches: [main]

  # once a day at 6:17 AM UTC
  schedule:
    - cron: "17 6 * * *"

  # manual execution
  workflow_dispatch:

  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions: read-all

jobs:
  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: oldstable
      - name: Test
        run: make builder-integration-test
